version: 0.2

phases:
  install:
    commands:
      # remove package-lock before updating npm, otherwise not all dependencies will install
      - rm package-lock.json
      # install global dependencies
      - npm install --silent --no-progress -g npm
      - npm uninstall --slient --no-progress -g serverless
      - npm install --silent --no-progress -g serverless
      - npm --version
  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install --silent --no-progress
  build:
    commands:
      - echo Running Unit Testing
      # run unit test
      - npm run test
      # create directory for deployment packages
      - mkdir artifacts
      # create staging deployment package
      - mkdir artifacts/stg
      - serverless package --package artifacts/stg --stage stg -v -r us-east-1
      # create prod deployment package
      - mkdir artifacts/prod
      - serverless package --package artifacts/prod --stage prod -v -r us-east-1

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh