version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm run setup
  build:
    commands:
      - echo Deploying to serverless...
      - serverless deploy
