app: serverless-covid19
# serverless.yml

service: covid-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 10 # optional
  tracing:
    lambda: true # optional
  environment:
    STAGE: ${opt:stage}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  serverless-offline:
    httpPort: 8080

plugins:
  - serverless-offline
  - serverless-mocha-plugin