app: serverless-covid19
# serverless.yml

service: serverless-covid19

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 10 # optional
  tracing:
    lambda: true # optional
  environment:
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
        - "s3:CreateBucket"
        - "s3:DeleteBucket"
        - "s3:ListBucket"
        - "s3:ListBucketVersions"
        - "s3:PutAccelerateConfiguration"
        - "s3:GetEncryptionConfiguration"
        - "s3:PutEncryptionConfiguration"
        - "s3:PutBucketAcl"
        - "s3:PutBucketPolicy"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# ONLY FOR DEVELOPMENT
custom:
  serverless-offline:
    httpPort: 8080
  output:
    file: .build/stack.json # where stack output should be stored by the serverless-stack-output plugin

# ONLY FOR DEVELOPMENT
plugins:
  - serverless-offline
  - serverless-stack-output