app: serverless-covid19
# serverless.yml

service: serverless-covid19

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 10 # optional
  tracing:
    lambda: true # optional
  environment:
    STAGE: ${opt:stage}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# ONLY FOR DEVELOPMENT
# custom:
#   serverless-offline:
#     httpPort: 8080

# ONLY FOR DEVELOPMENT
# plugins:
#   - serverless-offline
#   - serverless-mocha-plugin