# serverless.yml

service: api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 10 # optional
  tracing:
    lambda: true # optional

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  serverless-offline:
    httpPort: 8080

plugins:
  - serverless-offline